services:
  - type: web
    name: silmedy-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
    - key: FIREBASE_CREDENTIALS_PATH
      value: secrets/silmedy-23a1b-firebase-adminsdk-fbsvc-1e8c6b596b.json
    - key: FIREBASE_DB_URL
      value: https://silmedy-23a1b-default-rtdb.firebaseio.com
    - key: AWS_ACCESS_KEY_ID
      value: your-access-key
    - key: AWS_SECRET_ACCESS_KEY
      value: your-secret-key
    - key: AWS_REGION
      value: ap-northeast-2