name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/Silmedy_web
          git pull origin main
          docker stop silmedy_test_container || true
          docker rm silmedy_test_container || true
          docker build -t silmedy_test .
          docker run -d --env-file ./secrets/.env -p 5000:5000 --name silmedy_test_container silmedy_test
